/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (7.2.0).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package org.example.openapi.api;

import io.swagger.v3.oas.annotations.media.ExampleObject;
import org.example.openapi.dto.DogDto;
import org.example.openapi.dto.ErrorDto;
import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.Parameter;
import io.swagger.v3.oas.annotations.media.Content;
import io.swagger.v3.oas.annotations.media.Schema;
import io.swagger.v3.oas.annotations.responses.ApiResponse;
import io.swagger.v3.oas.annotations.tags.Tag;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.*;

import jakarta.validation.Valid;
import jakarta.annotation.Generated;

@Generated(value = "org.openapitools.codegen.languages.SpringCodegen")
@Validated
@Tag(name = "dogs", description = "the dogs API")
public interface DogsApi {

    default DogsApiDelegate getDelegate() {
        return new DogsApiDelegate() {};
    }

    /**
     * POST /dogs : Create a dog
     *
     * @param dogDto  (optional)
     * @return OK (status code 200)
     *         or Bad Request (status code 400)
     */
    @Operation(
        operationId = "createDog",
        summary = "Create a dog",
        responses = {
            @ApiResponse(responseCode = "200", description = "OK", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = DogDto.class))
            }),
            @ApiResponse(responseCode = "400", description = "Bad Request", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ErrorDto.class),
                        examples = {
                        @ExampleObject(name = "DogNameBiggerThan50Error",
                                value = "{\"code\": 400, \"message\": \"name size must be between 0 and 50\"}"),
                        @ExampleObject(name = "DogNameContainsNumbersError",
                                value = "{\"code\": 400, \"message\": \"Name must contain only letters\"}"),
                        @ExampleObject(name = "DogAgeNegativeError",
                                value = "{\"code\": 400, \"message\": \"age must be greater than or equal to 0\"}")
                })
            })
        }
    )
    @RequestMapping(
        method = RequestMethod.POST,
        value = "/dogs",
        produces = { "application/json" },
        consumes = { "application/json" }
    )
    
    default ResponseEntity<DogDto> createDog(
        @Parameter(name = "DogDto", description = "") @Valid @RequestBody(required = false) DogDto dogDto
    ) {
        return getDelegate().createDog(dogDto);
    }

}
